wtf:
  grid:
    columns: [35, 35, 35, 35, 0]
    rows: [10, 10, 5, 10, 0]
  refreshInterval: 1h
  openFileUtil: "xdg-open"
  opeUrlUtil: "xdg-open"
  exitMessage:
    display: false
  mods:
    khal:
      type: cmdrunner
      title: " Calendar"
      focusable: false
      cmd: "khal"
      args: ["list"]
      pty: true
      enabled: true
      position:
        top: 0
        left: 0
        height: 3
        width: 1
      refreshInterval: 1h
    battery:
      type: power
      title: "⚡️Power"
      enabled: true
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 15
    ip:
      type: ipinfo
      title: "󱦂 Info"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 1h
    network:
      type: security
      title: "󰀃 Network"
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 1
      refreshInterval: 1h
    disks:
      type: cmdrunner
      title: "󰨣 Disks"
      focusable: false
      cmd: "df"
      args: ["-h"]
      enabled: true
      position:
        top: 2
        left: 1
        height: 2
        width: 3
      refreshInterval: 1h
    prettyweather:
      enabled: true
      city: "Lima"
      title: " Weather"
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 5m
      unit: "m"
      view: 0
      language: "en"
    jira:
      focusable: false
      title: "󰌃 Jira"
      domain: "https://bandofcoders.atlassian.net"
      email: "geanb@bandofcoders.com"
      enabled: true
      position:
        top: 0
        left: 1
        height: 2
        width: 1
      project: "DP"
      refreshInterval: 1h
      username: "geanb@bandofcoders.com"
      verifyServerCertificate: true
