import = [
"~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]
live_config_reload = true

[window]
decorations = "full"

  [window.padding]
  x = 7
  y = 7

[font]
size = 10

  [font.normal]
  family = "IosevkaTerm NF"

  # [font.offset]
  # x = 0
  # y = 6
  #
  # [font.glyph_offset]
  # x = 0
  # y = 3

[cursor]
thickness = 0.3

  [cursor.style]
  shape = "Beam"
  blinking = "On"

  [cursor.vi_mode_style]
  shape = "Block"
  blinking = "On"

[mouse]
hide_when_typing = true
